### ISSUE TITLE
Able to authorize, But not able to getDefects 

### ISSUE THREAD

**Issue by mukesh3521** [webcompere/ALMRestClient#1]
First of all , the work you have did is really appreciable, 
I am able to authorize using this framework provided, But not able to getDefects.
When I am calling Get defects it returns unauthorized. 
Can't find what's the actual issue, Need serious help here .

**Comment by ashleyfrieze** [comment]
I can't offer a huge amount of help on this one, I'm afraid. It's been a while since I wrote that code. It's possible that you might not have access rights within the repo you're trying to query. It's also possible that the API has changed since the code was written and that the specific version you're using is more sensitive to the REST headers.

If you can post the full response from the API, I may be able to give you some clues.

Similarly, you can test it by repeating the same steps the code does, by using some sort of REST API helper in your favourite browser. There are good REST console plugins for Firefox and Chrome.

Good luck.

**Comment by mukesh3521** [comment]
Thanks for your immediate response, i was waiting for it , 
So far,  I am Calling Login Function, I get a response.StatusCode as Ok .
I am little bit aware about ( Rest Api Client Postman )Same I have also tried with google, Their also it works fine for me . 
Also, I am not much familiar with Postman also, so i am not able to get the defects their too, I get some QCsession Cookie not set error 

I am able to get the Token(returned on successful authentication  ) by  passing username and password , that means i have the access, same works with your code also.

I am calling like :  

```
        ALMClient almObj = new ALMClient(server, username, password, domain, project);
        almObj.Login();
        almObj.GetDefects();
```

So login works for me But GetDefects give a unauthorized exception . 

Please help me , I am spinning my head from a longer time to get it working .

**Comment by ashleyfrieze** [comment]
Hi Mukesh

I'm afraid there's a limit to what support I can offer for this code, and we're nearly at that limit.

Can you access those defects through the ALM UI?

Can you make a breakpoint inside my code to find out exactly what the response looks like, headers and body - https://github.com/webcompere/ALMRestClient/blob/master/ALMClient/ALMClient.cs#L113 is the location to break, I think.

**Comment by mukesh3521** [comment]
Hi ashley, 
It's long since i replied to this Issue thread, But i Found the issue , 
Due to changes in the Rest API , Now in login you may need to call another request to Get a QCSession cookie value set . 
Like this  In the Login :
IRestResponse response1 = client.Post(new RestRequest("rest/site-session"));
After this login function looks something like this :

 public void Login()
        {
            IRestResponse response = client.Post(new RestRequest("authentication-point/authenticate"));

```
        IRestResponse response1 = client.Post(new RestRequest("rest/site-session"));
        if (response.StatusCode != HttpStatusCode.OK)
        {
            throw new ALMClientException(response.StatusCode, "Error in login " + response.ErrorMessage, response.Content);
        }
        if (response1.StatusCode != HttpStatusCode.Created)
        {
            throw new ALMClientException(response.StatusCode, "Error in login " + response.ErrorMessage, response.Content);
        }


    }
```

I am still working on ALM rest API , Please reply to this i need to ask some more queries, I am really stuck Up, Please help me . :(

**Comment by ashleyfrieze** [comment]
Note - @Stevoni 's pull request may make life better for you. Please check it out. Contact him with questions. If this results in a new Pull Request, I'll authorise.

**Comment by chrismaran18** [comment]
Hi @ashleyfrieze 
I have cloned this source code... but I am getting this following errors. Could you please help me!

Build started...
1>------ Build started: Project: ALMRestClient, Configuration: Debug Any CPU ------
1>C:\Users\cs210142\Source\Repos\ALMRestClient\ALMClient\ALMClient.cs(10,7,10,17): warning CS0105: The using directive for 'System.Net' appeared previously in this namespace
1>C:\Users\cs210142\Source\Repos\ALMRestClient\ALMClient\HTMLCleanUp.cs(7,28,7,36): error CS0234: The type or namespace name 'MonoHttp' does not exist in the namespace 'RestSharp.Extensions' (are you missing an assembly reference?)
2>------ Build started: Project: ALMClientTests, Configuration: Debug Any CPU ------
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by ashleyfrieze** [comment]
@chrismaran18 - I no longer support this. You might ask for guidance from @Stevoni 

You may also wish to look at whether your RestSharp client is the right version.

**Comment by chrismaran18** [comment]
Okay thanks for your quick response @ashleyfrieze
